# Generated by Django 6.0.4 on 2026-06-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('temporada', models.CharField(max_length=50, verbose_name='Temporada (ej. 2025/2026)')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría (ej. Alevín, Infantil, Senior)')),
                ('entrenador_principal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entrenador Principal')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Jugadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dorsal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dorsal')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('posicion', models.CharField(blank=True, choices=[('COLOCADORA', 'Colocadora'), ('OPUESTA', 'Opuesta'), ('CENTRAL', 'Central'), ('RECEPTORA', 'Receptora'), ('LIBERO', 'Líbero')], max_length=20, null=True, verbose_name='Posición')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('talla_competicion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Talla de Competición')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadoras', to='stats_app.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Jugadora',
                'verbose_name_plural': 'Jugadoras',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Partido')),
                ('hora', models.TimeField(verbose_name='Hora del Partido')),
                ('rival', models.CharField(max_length=150, verbose_name='Rival')),
                ('local', models.BooleanField(default=True, verbose_name='¿Juega como Local?')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar/Pabellón')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='stats_app.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEstadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_numero', models.PositiveIntegerField(default=1)),
                ('tipo_fase', models.CharField(choices=[('K1', 'K1 (Recepción/Ataque)'), ('K2', 'K2 (Saque/Defensa)')], max_length=5)),
                ('accion', models.CharField(choices=[('SAQUE', 'Saque'), ('RECEPCION', 'Recepción'), ('COLOCACION', 'Colocación'), ('ATAQUE', 'Ataque'), ('BLOQUEO', 'Bloqueo'), ('DEFENSA', 'Defensa'), ('ERROR_RIVAL', 'Error del Rival'), ('PUNTO_RIVAL', 'Punto del Rival'), ('SUSTITUCION', 'Sustitución')], max_length=20)),
                ('calidad', models.CharField(blank=True, choices=[('++', '++'), ('+', '+'), ('=', '='), ('-', '-'), ('--', '--')], max_length=2, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('jugadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='stats_app.jugadora')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='stats_app.partido')),
            ],
            options={
                'verbose_name': 'Registro de Estadística',
                'verbose_name_plural': 'Registros de Estadísticas',
            },
        ),
        migrations.CreateModel(
            name='RotacionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_numero', models.PositiveIntegerField(default=1)),
                ('es_inicial', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones', to='stats_app.partido')),
                ('pos1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos1_rotaciones', to='stats_app.jugadora', verbose_name='Zona 1 (Saque)')),
                ('pos2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos2_rotaciones', to='stats_app.jugadora', verbose_name='Zona 2')),
                ('pos3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos3_rotaciones', to='stats_app.jugadora', verbose_name='Zona 3')),
                ('pos4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos4_rotaciones', to='stats_app.jugadora', verbose_name='Zona 4')),
                ('pos5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos5_rotaciones', to='stats_app.jugadora', verbose_name='Zona 5')),
                ('pos6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos6_rotaciones', to='stats_app.jugadora', verbose_name='Zona 6')),
            ],
            options={
                'verbose_name': 'Rotación de Set',
                'verbose_name_plural': 'Rotaciones de Sets',
            },
        ),
    ]
