# Generated by Django 5.2.11 on 2026-07-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugadora',
            name='talla_competicion',
        ),
        migrations.RemoveField(
            model_name='jugadora',
            name='telefono_contacto',
        ),
    ]
