# Generated by Django 6.0.4 on 2026-07-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0002_remove_jugadora_talla_competicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='modalidad',
            field=models.CharField(choices=[('VOLEY', 'Voleibol 6x6'), ('MINIVOLEY', 'Minivoley 4x4')], default='VOLEY', max_length=15, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='registroestadistica',
            name='rotacion_num',
            field=models.PositiveIntegerField(default=1, verbose_name='Rotación Activa'),
        ),
        migrations.AlterField(
            model_name='rotacionset',
            name='pos1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos1_rotaciones', to='stats_app.jugadora', verbose_name='Zona 1 (Saque)'),
        ),
        migrations.AlterField(
            model_name='rotacionset',
            name='pos2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos2_rotaciones', to='stats_app.jugadora', verbose_name='Zona 2'),
        ),
        migrations.AlterField(
            model_name='rotacionset',
            name='pos3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos3_rotaciones', to='stats_app.jugadora', verbose_name='Zona 3'),
        ),
        migrations.AlterField(
            model_name='rotacionset',
            name='pos4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos4_rotaciones', to='stats_app.jugadora', verbose_name='Zona 4'),
        ),
        migrations.AlterField(
            model_name='rotacionset',
            name='pos5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos5_rotaciones', to='stats_app.jugadora', verbose_name='Zona 5'),
        ),
        migrations.AlterField(
            model_name='rotacionset',
            name='pos6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos6_rotaciones', to='stats_app.jugadora', verbose_name='Zona 6'),
        ),
    ]
