# Generated by Django 6.0.4 on 2026-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0003_partido_modalidad_registroestadistica_rotacion_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
