# Generated by Django 6.0.4 on 2026-07-04 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0004_partido_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotacionset',
            name='libero1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libero1_rotaciones', to='stats_app.jugadora', verbose_name='Líbero 1'),
        ),
        migrations.AddField(
            model_name='rotacionset',
            name='libero2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libero2_rotaciones', to='stats_app.jugadora', verbose_name='Líbero 2'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(choices=[('BENJAMIN', 'Benjamín'), ('ALEVIN', 'Alevín'), ('INFANTIL', 'Infantil'), ('CADETE', 'Cadete'), ('JUVENIL', 'Juvenil'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], default='SENIOR', max_length=20, verbose_name='Categoría'),
        ),
    ]
