# Generated by Django 6.0.4 on 2026-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0006_data_migration_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='puntos_por_set',
            field=models.PositiveIntegerField(default=25, verbose_name='Puntos por set'),
        ),
        migrations.AddField(
            model_name='partido',
            name='puntos_set_decisivo',
            field=models.PositiveIntegerField(default=15, verbose_name='Puntos del set decisivo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='sets_para_ganar',
            field=models.PositiveIntegerField(default=3, verbose_name='Sets para ganar el partido'),
        ),
    ]
