# Generated by Django 6.0.4 on 2026-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0010_equipo_entrenador_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroestadistica',
            name='zona',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Zona de la pista (1-6) desde la que se ejecutó la acción en Modo Rápido. Nulo para acciones sin zona propia (Colocación, líbero, Modo Avanzado, puntos de rival, etc.).', null=True, verbose_name='Zona del campo'),
        ),
    ]
