# Generated by Django 5.2.11 on 2026-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0011_registroestadistica_zona'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registroestadistica',
            index=models.Index(fields=['partido', 'set_numero'], name='statsapp_reg_partido_set_idx'),
        ),
    ]
