# Generated by Django 5.2.11 on 2026-07-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0012_registroestadistica_statsapp_reg_partido_set_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='informe_pdf_cache',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='informe_pdf_cache_generado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='informe_pdf_cache_num_registros',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
