# Generated by Django 5.2.11 on 2026-07-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0013_partido_informe_pdf_cache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroestadistica',
            name='accion',
            field=models.CharField(choices=[('SAQUE', 'Saque'), ('RECEPCION', 'Recepción'), ('COLOCACION', 'Colocación'), ('ATAQUE', 'Ataque'), ('BLOQUEO', 'Bloqueo'), ('DEFENSA', 'Defensa'), ('ERROR_RIVAL', 'Error del Rival'), ('PUNTO_RIVAL', 'Punto del Rival'), ('SUSTITUCION', 'Sustitución'), ('RED', 'Red')], max_length=20),
        ),
    ]
