# Generated by Django 5.2.11 on 2026-07-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0015_partido_informe_avanzado_pdf_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_numero', models.PositiveIntegerField(default=1, verbose_name='Set')),
                ('texto', models.TextField(max_length=2000, verbose_name='Texto')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('jugadora', models.ForeignKey(blank=True, help_text='Vacío = nota general del partido.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas_partido', to='stats_app.jugadora', verbose_name='Jugadora')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='stats_app.partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Nota de partido',
                'verbose_name_plural': 'Notas de partido',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['partido', 'set_numero'], name='statsapp_nota_partido_set_idx')],
            },
        ),
    ]
