# Generated by Django 6.0.4 on 2026-08-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0018_registroestadistica_zona_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('TITULAR', 'Titular'), ('ALINEACION_B', 'Alineación B')], max_length=20, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_presets', to='stats_app.equipo', verbose_name='Equipo')),
                ('libero1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libero1_presets', to='stats_app.jugadora', verbose_name='Líbero 1')),
                ('libero2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libero2_presets', to='stats_app.jugadora', verbose_name='Líbero 2')),
                ('pos1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos1_presets', to='stats_app.jugadora', verbose_name='Zona 1 (Saque)')),
                ('pos2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos2_presets', to='stats_app.jugadora', verbose_name='Zona 2')),
                ('pos3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos3_presets', to='stats_app.jugadora', verbose_name='Zona 3')),
                ('pos4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos4_presets', to='stats_app.jugadora', verbose_name='Zona 4')),
                ('pos5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos5_presets', to='stats_app.jugadora', verbose_name='Zona 5')),
                ('pos6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos6_presets', to='stats_app.jugadora', verbose_name='Zona 6')),
            ],
            options={
                'verbose_name': 'Plantilla de alineación',
                'verbose_name_plural': 'Plantillas de alineación',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('equipo', 'clave'), name='uniq_lineup_preset_equipo_clave')],
            },
        ),
    ]
