# Generated by Django 5.2.11 on 2026-09-04 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0020_jugadora_fecha_nacimiento_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convocatoria', to='stats_app.partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
            },
        ),
        migrations.CreateModel(
            name='ConvocatoriaJugadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocada', models.BooleanField(default=True, verbose_name='Convocada')),
                ('motivo_baja', models.CharField(blank=True, choices=[('LESION', 'Lesión'), ('ENFERMEDAD', 'Enfermedad'), ('ESTUDIOS', 'Estudios'), ('VIAJE', 'Viaje'), ('SANCION', 'Sanción'), ('ROTACION', 'Rotación'), ('DECISION_TECNICA', 'Decisión técnica'), ('OTRO', 'Otro')], max_length=20, null=True, verbose_name='Motivo de baja')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='stats_app.convocatoria', verbose_name='Convocatoria')),
                ('jugadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_convocatoria', to='stats_app.jugadora', verbose_name='Jugadora')),
            ],
            options={
                'verbose_name': 'Jugadora en convocatoria',
                'verbose_name_plural': 'Jugadoras en convocatoria',
                'constraints': [models.UniqueConstraint(fields=('convocatoria', 'jugadora'), name='uniq_convocatoria_jugadora')],
            },
        ),
    ]
